name: novum
description: A news app built with flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.3+2

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.12.2
  transparent_image: ^0.1.0
  flutter_villains: ^1.2.0
  share: ^2.0.0
  flutter_custom_tabs: ^0.6.0
  newsapi_client: ^0.2.5+1
  flutter_sparkline: ^0.1.0
  shared_preferences: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: assets/icons/icon-710.png
  android: true
  ios: true
  adaptive_icon_background: assets/icons/icon-background.png
  adaptive_icon_foreground: assets/icons/icon-foreground.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: Eczar
      fonts:
        - asset: assets/fonts/Eczar-Regular.ttf
          weight: 400
        - asset: assets/fonts/Eczar-SemiBold.ttf
          weight: 600
    - family: Libre Franklin
      fonts:
        - asset: assets/fonts/LibreFranklin-Light.ttf
          weight: 300
        - asset: assets/fonts/LibreFranklin-Regular.ttf
          weight: 400
        - asset: assets/fonts/LibreFranklin-Medium.ttf
          weight: 500
        - asset: assets/fonts/LibreFranklin-Bold.ttf
          weight: 700
